name: Update OpenAPI Specification

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'aws-sam-assassin/src/main/java/com/assassin/handlers/**'
      - 'aws-sam-assassin/src/main/java/com/assassin/util/ApiEndpoint.java'
      - 'aws-sam-assassin/src/main/java/com/assassin/util/OpenApiGenerator.java'
  pull_request:
    paths:
      - 'aws-sam-assassin/src/main/java/com/assassin/handlers/**'
  workflow_dispatch:

jobs:
  update-openapi:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Compile project
      working-directory: ./aws-sam-assassin
      run: mvn compile -q
    
    - name: Generate OpenAPI specification
      working-directory: ./aws-sam-assassin
      run: mvn exec:java -Dexec.mainClass="com.assassin.util.OpenApiGenerator" -Dexec.classpathScope="compile" -q
    
    - name: Install API validation tools
      run: |
        npm install -g @apidevtools/swagger-cli
        npm install -g @stoplight/spectral-cli
    
    - name: Validate OpenAPI specification
      run: |
        swagger-cli validate docs/openapi.yaml
        spectral lint docs/openapi.yaml --ruleset https://raw.githubusercontent.com/stoplightio/spectral/master/docs/reference/openapi-rules.md
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        git diff --name-only docs/openapi.yaml
        if [[ $(git status --porcelain docs/openapi.yaml) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.verify-changed-files.outputs.changes == 'true' && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/openapi.yaml
        git commit -m "🔄 Update OpenAPI specification from handler annotations"
        git push
    
    - name: Comment PR
      if: steps.verify-changed-files.outputs.changes == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🔄 **OpenAPI Specification Update Required**\n\nChanges to handler files detected. Please run `./scripts/update-openapi.sh` locally and commit the updated `docs/openapi.yaml` file.'
          })
    
    - name: Upload OpenAPI artifact
      uses: actions/upload-artifact@v4
      with:
        name: openapi-spec
        path: docs/openapi.yaml
    
    - name: Generate API documentation
      run: |
        npx @redocly/cli build-docs docs/openapi.yaml -o docs/api-docs.html
    
    - name: Upload API documentation
      uses: actions/upload-artifact@v4
      with:
        name: api-documentation
        path: docs/api-docs.html